//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlbClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGameScoreRequest", Namespace="http://schemas.datacontract.org/2004/07/MlbData.Services.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetGameScoreRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGameScoreResponse", Namespace="http://schemas.datacontract.org/2004/07/MlbData.Services.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetGameScoreResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MlbClient.ServiceReference1.GameResult[] GameResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MlbClient.ServiceReference1.GameResult[] GameResults {
            get {
                return this.GameResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.GameResultsField, value) != true)) {
                    this.GameResultsField = value;
                    this.RaisePropertyChanged("GameResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameResult", Namespace="http://schemas.datacontract.org/2004/07/MlbData.Services.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AwayRunsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AwayTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HomeRunsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTeamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AwayRuns {
            get {
                return this.AwayRunsField;
            }
            set {
                if ((this.AwayRunsField.Equals(value) != true)) {
                    this.AwayRunsField = value;
                    this.RaisePropertyChanged("AwayRuns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HomeRuns {
            get {
                return this.HomeRunsField;
            }
            set {
                if ((this.HomeRunsField.Equals(value) != true)) {
                    this.HomeRunsField = value;
                    this.RaisePropertyChanged("HomeRuns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGameScoresForDateRequest", Namespace="http://schemas.datacontract.org/2004/07/MlbData.Services.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetGameScoresForDateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGameScoreService")]
    public interface IGameScoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameScoreService/GetGameScoreForTeam", ReplyAction="http://tempuri.org/IGameScoreService/GetGameScoreForTeamResponse")]
        MlbClient.ServiceReference1.GetGameScoreResponse GetGameScoreForTeam(MlbClient.ServiceReference1.GetGameScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameScoreService/GetGameScoreForTeam", ReplyAction="http://tempuri.org/IGameScoreService/GetGameScoreForTeamResponse")]
        System.Threading.Tasks.Task<MlbClient.ServiceReference1.GetGameScoreResponse> GetGameScoreForTeamAsync(MlbClient.ServiceReference1.GetGameScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameScoreService/GetGameScoresForDate", ReplyAction="http://tempuri.org/IGameScoreService/GetGameScoresForDateResponse")]
        MlbClient.ServiceReference1.GetGameScoreResponse GetGameScoresForDate(MlbClient.ServiceReference1.GetGameScoresForDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameScoreService/GetGameScoresForDate", ReplyAction="http://tempuri.org/IGameScoreService/GetGameScoresForDateResponse")]
        System.Threading.Tasks.Task<MlbClient.ServiceReference1.GetGameScoreResponse> GetGameScoresForDateAsync(MlbClient.ServiceReference1.GetGameScoresForDateRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameScoreServiceChannel : MlbClient.ServiceReference1.IGameScoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameScoreServiceClient : System.ServiceModel.ClientBase<MlbClient.ServiceReference1.IGameScoreService>, MlbClient.ServiceReference1.IGameScoreService {
        
        public GameScoreServiceClient() {
        }
        
        public GameScoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameScoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MlbClient.ServiceReference1.GetGameScoreResponse GetGameScoreForTeam(MlbClient.ServiceReference1.GetGameScoreRequest request) {
            return base.Channel.GetGameScoreForTeam(request);
        }
        
        public System.Threading.Tasks.Task<MlbClient.ServiceReference1.GetGameScoreResponse> GetGameScoreForTeamAsync(MlbClient.ServiceReference1.GetGameScoreRequest request) {
            return base.Channel.GetGameScoreForTeamAsync(request);
        }
        
        public MlbClient.ServiceReference1.GetGameScoreResponse GetGameScoresForDate(MlbClient.ServiceReference1.GetGameScoresForDateRequest request) {
            return base.Channel.GetGameScoresForDate(request);
        }
        
        public System.Threading.Tasks.Task<MlbClient.ServiceReference1.GetGameScoreResponse> GetGameScoresForDateAsync(MlbClient.ServiceReference1.GetGameScoresForDateRequest request) {
            return base.Channel.GetGameScoresForDateAsync(request);
        }
    }
}
